<a href="https://colab.research.google.com/github/priyanka22wh1a1264/DataAnalysis/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Task**

Part 1: Creating and Reshaping Arrays

1. Create Arrays:

Create two NumPy arrays:

▪ A 1D array of 10 equally spaced values between 0 and 50.

▪ A 2D array of shape (3x3) containing random integers
between 5 and 20.

In [12]:
import numpy as np

In [13]:
a1=np.linspace(1,50,10)
a1
a2=np.random.randint(5,21,9)
a3=a2.reshape(3,3)
a3

array([[14, 13,  9],
       [15, 19,  7],
       [ 7, 18, 19]])

2. Array Dimensions:

Print the dimensions of both arrays.

Print the shape of both arrays.


In [14]:
print(a1.ndim,a3.ndim)
print(a1.shape,a3.shape)

1 2
(10,) (3, 3)


3. Reshaping:

Reshape the 1D array into a 2D array with shape (2x5).

Print the reshaped array.

Flatten the reshaped array back to 1D and print it.

In [15]:
a1_reshaped = a1.reshape(2,5)
print(a1_reshaped)
a1_f = a1_reshaped.flatten()
print(a1_f)

[[ 1.          6.44444444 11.88888889 17.33333333 22.77777778]
 [28.22222222 33.66666667 39.11111111 44.55555556 50.        ]]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


Part 2: Indexing and Slicing

4. Indexing:

For the 2D array created in Part 1, print the element present at the
2nd row and 3rd column.

Extract the first two rows and the last two columns of the array.

In [16]:
print(a3)
print(a3[:2, -2:])

[[14 13  9]
 [15 19  7]
 [ 7 18 19]]
[[13  9]
 [19  7]]


5. Slicing:

Slice the first four elements from the flattened 1D array.

Reverse the elements of the 1D array using slicing.

In [18]:
print("\nFirst four elements of flattened 1D array:", a1_f[:4])
print("Reversed 1D array:", a1_f[::-1])


First four elements of flattened 1D array: [ 1.          6.44444444 11.88888889 17.33333333]
Reversed 1D array: [50.         44.55555556 39.11111111 33.66666667 28.22222222 22.77777778
 17.33333333 11.88888889  6.44444444  1.        ]


Part 3: Array Operations

6. Array Arithmetic:

Create another 1D array of 10 integers between 1 and 10.

Perform the following element-wise operations between the 1D

arrays created in Part 1 and Part 3:

▪ Addition

▪ Multiplication

▪ Subtract a constant value (e.g., 5) from the array.


In [19]:
arr1d2 = np.arange(1, 11)
print("\nAddition:\n", a1 + arr1d2)
print("Multiplication:\n", a1 * arr1d2)
print("Subtract 5 from array:\n", a1 - 5)


Addition:
 [ 2.          8.44444444 14.88888889 21.33333333 27.77777778 34.22222222
 40.66666667 47.11111111 53.55555556 60.        ]
Multiplication:
 [  1.          12.88888889  35.66666667  69.33333333 113.88888889
 169.33333333 235.66666667 312.88888889 401.         500.        ]
Subtract 5 from array:
 [-4.          1.44444444  6.88888889 12.33333333 17.77777778 23.22222222
 28.66666667 34.11111111 39.55555556 45.        ]


Part 4: Random Number Generation and Copying

7. Random Numbers:

Create a 1D array of 5 random values between 0 and 1.

Create another 1D array of 5 random values between -1 and 1.


In [20]:
rand1 = np.random.rand(5)
rand2 = np.random.uniform(-1, 1, 5)
print("Random values between 0 and 1:\n", rand1)
print("Random values between -1 and 1:\n", rand2)

Random values between 0 and 1:
 [0.87450081 0.19416675 0.41782641 0.84595815 0.02597861]
Random values between -1 and 1:
 [ 0.38132056 -0.40110331 -0.39296056  0.63984801  0.43991343]


Part 5: Bonus

8. Challenge Task:

Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.

Find the sum of all the elements in the array and print the result.

In [21]:
n = int(input("Enter n: "))
a = np.random.randint(1, 101, n*n)
print("1D array:\n", a)
a_2d = a.reshape(n, n)
print("Reshaped n x n array:\n", a_2d)
print("Sum of all elements:", np.sum(a))

Enter n: 5
1D array:
 [83 48 82 95 84 18  1 99 14 58 84 76 92 52 35 50 67 48 23 18 87 70 25 49
 95]
Reshaped n x n array:
 [[83 48 82 95 84]
 [18  1 99 14 58]
 [84 76 92 52 35]
 [50 67 48 23 18]
 [87 70 25 49 95]]
Sum of all elements: 1453
